### PR TITLE
Add base64enc to dependencies list

### PR DESCRIPTION
**Pull request by jluxenberg**
Got the following error when trying to use this for the first time:

> setup_twitter_oauth(...)
[1] "Using browser based authentication"
Use a local file to cache OAuth access credentials between R sessions?
1: Yes
2: No

Selection: 1
Adding .httr-oauth to .gitignore
Error in loadNamespace(name) : there is no package called ‘base64enc’

### CODE REVIEW

**Comment by jluxenberg** [comment]
Also need httpuv. Updated PR.

**Comment by geoffjentry** [comment]
twitteR doesn't depend on either of those, httr does. How did you install httr?

**Comment by jluxenberg** [comment]
Ah, that explains it. Maybe I didn't check the "install dependencies" box when I installed httr. (installed via the package manager UI)

**Comment by geoffjentry** [comment]
Ah, that'd do it :)

**Pull request closed without merging**
