### PR TITLE
Oauth httr v1.0

### LINKED ISSUE #90: Error in check_twitter_oauth( )
I know this issue has come up before when Hadley has made changes to his httr package, but I wanted to bring it to your attention again as he just pushed version 1.0.0.9000 and it seems to be causing the same issue. The following works as a workaround in the meantime.
```
devtools::install_version("httr", version="0.6.0", repos="http://cran.us.r-project.org")
```
Just be sure to restart R after running the command.

### PR DESCRIPTION
**Pull request by jrowen**
I believe this fixes #90 by reimplementing the http v0.6 logic in this package.

### CODE REVIEW

**Comment by geoffjentry** [comment]
@jrowen Thanks for submitting this! It's not working for me though, should this be a drop in replacement?

**Comment by geoffjentry** [comment]
@jrowen Disregard - after trying to figure it out myself I got it working and then looked back here and realized our solutions were nearly identical. I tried reloading your version and it works fine. Presumably operator error on my part.  Thanks again!

**Comment by jrowen** [comment]
Glad it worked out.

**Comment by theRanalyst** [comment]
With @geoffjentry's merge into master, I was under the impression that I could just reinstall twitteR via `devtools::install_github` but that doesn't seem to have worked. I also upgraded `httr` to version 1.0.0.9000 and restarted RStudio, but it is no issuing the same error as before. Should I be installing @jrowen's branch as well?

**Comment by jrowen** [comment]
This is working for me with httr v1.0 and the latest version of twitteR on
github.  You should no longer need to install my fork.  When prompted for
direct authentication choose No.

**Comment by geoffjentry** [comment]
@theRanalyst It's interesting that you say that because I had the exact same problem at first when I was testing @jrowen PR. Then I went and fiddled with it for a bit and a while later tried it again (without reason to believe anything was different) and it worked.

It could be that the local caching that httr does is invalid, I believe when I ran it the second time I was in a different directory.

**Comment by theRanalyst** [comment]
Here is what I get in a brand new R session:
```
> library(httr)
> library(twitteR)
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] twitteR_1.1.8   httr_1.0.0.9000

loaded via a namespace (and not attached):
[1] bit_1.1-12         rjson_0.2.15       R6_2.1.0          
[4] magrittr_1.5       DBI_0.3.1          tools_3.2.0       
[7] bit64_0.9-5        stringi_0.5-5      stringr_1.0.0.9000
> source("~/Dropbox/R/twitterKeys.R")
> setup_twitter_oauth(consumerKey, consumerSecret, oauthKey, oauthSecret)
[1] "Using direct authentication"
Use a local file to cache OAuth access credentials between R sessions?
1: Yes
2: No

Selection: 2
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'
>
```

**Comment by theRanalyst** [comment]
@geoffjentry One thing I've noticed is that if I choose Yes when prompted to use a local file to cache OAuth, it doesn't create a .httr-oauth file as I would expect. It gets added to my .gitignore file, but there is no actual .httr-oauth file to access. It's possible this is causing me an issue as well.

**Comment by geoffjentry** [comment]
@theRanalyst One thing to try would be to do Hadley's demo by hand and then in a new R session try the new twitteR, as that's effectively what I did. As I said I also was in a different directory (I wasn't using RStudio) when it did work although not intentionally.

Those are the only two things I can think of that happened between the first time I ran it and when it worked. 

You might try doing a find on .httr-oauth, perhaps it's getting created somewhere you don't expect? Not sure how that would work with RStudio.

**Comment by jrowen** [comment]
You can also try using `debug(twitteR:::get_twitter_token_via_sign)` to see if you can track down where the error occurs.

Another option could be to remove all packages using `remove.packages` (or the x in the RStudio package pane) and then re-install.

**Comment by theRanalyst** [comment]
@jrowen @geoffjentry Thanks for the advice. I've gone through what you've suggested and here's what I found. Using the debug function didn't help because it made it all the way through the function but then exited with the same error we were all getting before. However, working through Hadley's demo did help. The issue ended up being a package that wasn't installed.

###### You have to have the `base64enc` package installed in order for this to work properly.

Aside from that, everything appears to be work as one would hope. Nice work, guys!

**Comment by sfirke** [comment]
@theRanalyst good call on having the *base64enc* package loaded - that fixed things for me, thanks!

**Pull request merged**
